version: '3.8'

services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080"
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=text2vec-openai
      - ENABLE_MODULES=text2vec-openai
      - OPENAI_APIKEY=${OPENAI_API_KEY}
    volumes:
      - weaviate_data:/var/lib/weaviate

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - VECTOR_PROVIDER=weaviate
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_INDEX_NAME=notes
    depends_on:
      - mongo
      - weaviate
    volumes:
      - ./backend:/app
    working_dir: /app
    command: npm run dev

  frontend-react:
    build:
      context: ./frontend/app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/app:/app
    working_dir: /app
    command: npm run dev
    depends_on:
      - backend

  frontend-svelte:
    build:
      context: ./frontend/landing
    ports:
      - "3001:3000"
    volumes:
      - ./frontend/landing:/app
    working_dir: /app
    command: npm run dev
    depends_on:
      - backend

volumes:
  weaviate_data:
